name: validate
on: push
jobs:
  quality-checks:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16.13.1
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
      - run: npm ci
      - run: npm run lint
      - run: npm test
        env: SLOW=1
